title: Notre-Dame de Paris
baseURL: https://www.srmasig.org/
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: bg-black
  description: ''  
  linkedin: ''
  mastodon: 'https://fediscience.org/@srmasig'
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  slack: ''
  twitter: 'https://bsky.app/profile/srma-sig.bsky.social'
  stackoverflow: ''
  youtube: ''
